-- AlterTable
ALTER TABLE "User" ADD COLUMN "aiCoachingUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiAnalysisUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "aiChartUsed" INTEGER NOT NULL DEFAULT 0;
